import { Gate, GateType } from './types';

export const GATES: Record<GateType, Gate> = {
  AND: {
    name: 'AND',
    description: 'Output is true only if all inputs are true.',
    numInputs: 3,
    logic: (a, b, c) => a && b && c,
    truthTable: [
      { A: 0, B: 0, C: 0, Output: 0 },
      { A: 0, B: 0, C: 1, Output: 0 },
      { A: 0, B: 1, C: 0, Output: 0 },
      { A: 0, B: 1, C: 1, Output: 0 },
      { A: 1, B: 0, C: 0, Output: 0 },
      { A: 1, B: 0, C: 1, Output: 0 },
      { A: 1, B: 1, C: 0, Output: 0 },
      { A: 1, B: 1, C: 1, Output: 1 },
    ],
    svgPath: 'M0,10 h30 a20,20 0 1 1 0,40 h-30 z',
    svgInvertCircle: false,
  },
  OR: {
    name: 'OR',
    description: 'Output is true if at least one input is true.',
    numInputs: 3,
    logic: (a, b, c) => a || b || c,
    truthTable: [
        { A: 0, B: 0, C: 0, Output: 0 },
        { A: 0, B: 0, C: 1, Output: 1 },
        { A: 0, B: 1, C: 0, Output: 1 },
        { A: 0, B: 1, C: 1, Output: 1 },
        { A: 1, B: 0, C: 0, Output: 1 },
        { A: 1, B: 0, C: 1, Output: 1 },
        { A: 1, B: 1, C: 0, Output: 1 },
        { A: 1, B: 1, C: 1, Output: 1 },
    ],
    svgPath: 'M0,10 C10,20 10,40 0,50 Q30,30 50,30 Q30,30 0,10',
    svgInvertCircle: false,
  },
  NOT: {
    name: 'NOT',
    description: 'Output is the inverse of the input.',
    numInputs: 1,
    logic: (a) => !a,
    truthTable: [
      { A: 0, Output: 1 },
      { A: 1, Output: 0 },
    ],
    svgPath: 'M0,10 l40,20 l-40,20 z',
    svgInvertCircle: true,
  },
  NAND: {
    name: 'NAND',
    description: 'Output is false only if all inputs are true (negated AND).',
    numInputs: 2,
    logic: (a, b) => !(a && b),
    truthTable: [
      { A: 0, B: 0, Output: 1 },
      { A: 0, B: 1, Output: 1 },
      { A: 1, B: 0, Output: 1 },
      { A: 1, B: 1, Output: 0 },
    ],
    svgPath: 'M0,10 h30 a20,20 0 1 1 0,40 h-30 z',
    svgInvertCircle: true,
  },
  NOR: {
    name: 'NOR',
    description: 'Output is true only if all inputs are false (negated OR).',
    numInputs: 2,
    logic: (a, b) => !(a || b),
    truthTable: [
      { A: 0, B: 0, Output: 1 },
      { A: 0, B: 1, Output: 0 },
      { A: 1, B: 0, Output: 0 },
      { A: 1, B: 1, Output: 0 },
    ],
    svgPath: 'M0,10 C10,20 10,40 0,50 Q30,30 50,30 Q30,30 0,10',
    svgInvertCircle: true,
  },
  XOR: {
    name: 'XOR',
    description: 'Output is true if an odd number of inputs are true.',
    numInputs: 3,
    logic: (a, b, c) => (a !== b) !== c,
    truthTable: [
      { A: 0, B: 0, C: 0, Output: 0 },
      { A: 0, B: 0, C: 1, Output: 1 },
      { A: 0, B: 1, C: 0, Output: 1 },
      { A: 0, B: 1, C: 1, Output: 0 },
      { A: 1, B: 0, C: 0, Output: 1 },
      { A: 1, B: 0, C: 1, Output: 0 },
      { A: 1, B: 1, C: 0, Output: 0 },
      { A: 1, B: 1, C: 1, Output: 1 },
    ],
    svgPath: 'M5,10 C15,20 15,40 5,50 Q35,30 55,30 Q35,30 5,10 M0,10 C10,20 10,40 0,50',
    svgInvertCircle: false,
  },
  XNOR: {
    name: 'XNOR',
    description: 'Output is true if an even number of inputs are true.',
    numInputs: 3,
    logic: (a, b, c) => !((a !== b) !== c),
    truthTable: [
      { A: 0, B: 0, C: 0, Output: 1 },
      { A: 0, B: 0, C: 1, Output: 0 },
      { A: 0, B: 1, C: 0, Output: 0 },
      { A: 0, B: 1, C: 1, Output: 1 },
      { A: 1, B: 0, C: 0, Output: 0 },
      { A: 1, B: 0, C: 1, Output: 1 },
      { A: 1, B: 1, C: 0, Output: 1 },
      { A: 1, B: 1, C: 1, Output: 0 },
    ],
    svgPath: 'M5,10 C15,20 15,40 5,50 Q35,30 55,30 Q35,30 5,10 M0,10 C10,20 10,40 0,50',
    svgInvertCircle: true,
  },
};